name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        architecture: x64
    - name: Build
      run: ./scripts/build.sh
    - name: Test
      run: ./scripts/test.sh
